#pragma once

#define SGCMD_CONNECT			10
#define SGCMD_USERDATA			11
#define SGCMD_DISCONNECT		12
#define SGCMD_USERLOADED		13

#define SGCMD_PLAYER_MOVE		0X1001
#define SGCMD_PLAYER_JOIN		0X1002
#define SGCMD_PLAYER_LEAVE		0X1003

#define SGWAREHOUSE_COUNT		80
#define SGEQUIPMENT_COUNT		7
#define SGBAG_MAXCOUNT			20

#define SGEQUIPMENT_HEAD		0
#define SGEQUIPMENT_HAND		1
#define SGEQUIPMENT_CLOTHES		2
#define SGEQUIPMENT_LEG			3
#define SGEQUIPMENT_FOOT		4
#define SGEQUIPMENT_LHAND		5
#define SGEQUIPMENT_RHAND		6
#define SGEQUIPMENT_PET			7

#define SGITEMTYPE_HAT			0
#define SGITEMTYPE_GLOVE		1
#define SGITEMTYPE_CLOTHES		2	
#define SGITEMTYPE_TROUSERS		3
#define SGITEMTYPE_SHOES		4
#define SGITEMTYPE_SWORD		5
#define SGITEMTYPE_KNIFE		6
#define SGITEMTYPE_BLADE		7
#define SGITEMTYPE_PET			8

#define SGACTORTYPE_NPC			0
#define SGACTORTYPE_PLAYER		1
#define SGACTORTYPE_PROPS		2

#define SGACTIONMASK_QUEST		0x0001
#define SGACTIONMASK_TALK		0x0002
#define SGACTIONMASK_TRADE		0x0004
#define SGACTIONMASK_OPERATE	0x0008

typedef struct SGCMD_PLAYER_MOVE_T {
	float fFromX, fFromY, fFromZ;
	float fToX, fToY, fToZ;
	unsigned int nTime;
} SGCMD_PLAYER_MOVE_T;
