#pragma once

#define SGEQUIPMENT_COUNT			7
#define SGBAG_MAX					20
#define SGWAREHOUSE_MAX				80

#define SGEQUIPMENT_HEAD			0
#define SGEQUIPMENT_HAND			1
#define SGEQUIPMENT_CLOTHES			2
#define SGEQUIPMENT_LEG				3
#define SGEQUIPMENT_FOOT			4
#define SGEQUIPMENT_LHAND			5
#define SGEQUIPMENT_RHAND			6
#define SGEQUIPMENT_PET				7

#define SGITEMTYPE_HAT				0
#define SGITEMTYPE_GLOVE			1
#define SGITEMTYPE_CLOTHES			2	
#define SGITEMTYPE_TROUSERS			3
#define SGITEMTYPE_SHOES			4
#define SGITEMTYPE_SWORD			5
#define SGITEMTYPE_KNIFE			6
#define SGITEMTYPE_BLADE			7
#define SGITEMTYPE_PET				8

#define SGACTORTYPE_NPC				0
#define SGACTORTYPE_PLAYER			1
#define SGACTORTYPE_PET				2
#define SGACTORTYPE_BATTLEFIELD		3
#define SGACTORTYPE_PROPS			4

#define SGACTIONMASK_QUEST			0x0001
#define SGACTIONMASK_TALK			0x0002
#define SGACTIONMASK_TRADE			0x0004
#define SGACTIONMASK_OPERATE		0x0008

#define SGBATTLEFIELD_TEAM_RED		0
#define SGBATTLEFIELD_TEAM_BLUE		1

typedef struct SGPLAYER_VIEWDATA {
	char name[100];
	char guild[100];
} SGPLAYER_VIEWDATA;

typedef struct SGNPC_VIEWDATA {
	char name[100];
} SGNPC_VIEWDATA;

typedef struct SGPET_VIEWDATA {
	unsigned int m_nOwner;
} SGPET_VIEWDATA;

typedef struct SGBATTLEFIELD_VIEWDATA {
	char name[100];
} SGBATTLEFIELD_VIEWDATA;