
all:
	cd src; make $@; cd ..
	cd tools; make $@; cd ..
	cd test; make $@; cd ..

clean:
	cd src; make $@; cd ..
	cd tools; make $@; cd ..
	cd test; make $@; cd ..

linux:
	cp -f Makefile.def.$@ Makefile.def

freebsd:
	cp -f Makefile.def.$@ Makefile.def

