#pragma once

#define SGWAREHOUSE_COUNT		80
#define SGEQUIPMENT_COUNT		7

#define SGEQUIPMENT_HEAD		0
#define SGEQUIPMENT_HAND		1
#define SGEQUIPMENT_CLOTH		2
#define SGEQUIPMENT_LEG			3
#define SGEQUIPMENT_FOOT		4
#define SGEQUIPMENT_LHAND		5
#define SGEQUIPMENT_RHAND		6
#define SGEQUIPMENT_PET			7

#define SGITEMTYPE_ARMOR		10
#define SGITEMTYPE_WEAPON		11
#define SGITEMTYPE_PET			12
