
#define CUBE_LOGIN_TOKEN_LEN		100
#define CUBE_NICK_LEN				32
#define CUBE_ROLEINFO_LEN			500
#define CUBE_WAREHOUSE_LEN			(1024)
#define CUBE_EQUIPMENT_LEN			(1024)

#define CUBE_ROOM_NAME_LEN			30
#define CUBE_ROOM_MEMBER_MAX		20
#define CUBE_ROOM_POSITION_LEN		60
#define CUBE_ROOM_MAP_LEN			40
#define CUBE_ROOM_SONG_LEN			100

#define CUBE_ROOM_STATE_ACTIVE		0
#define CUBE_ROOM_STATE_GAMING		1
#define CUBE_ROOM_STATE_LOADING		2
