
!#include "LuaDebugInfo.h"

LuaDebugHostRpc_Attach();
LuaDebugHostRpc_Detach();

LuaDebugHostRpc_GetCallStack(
	[OUT("*depth")] LUADEBUG_CALLSTACK stacks["*depth"],
	[IN OUT] int depth["1"]
);

LuaDebugHostRpc_RunCmd(
	[IN] char Cmd["strlen(Cmd)+1"]
);
